[project]
name = "auto-fingerprint"
version = "0.1.0"
description = ""
authors = [{ name = "Armin Sabouri", email = "me@arminsabouri.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai (==1.82.1)",
    "numpy (>=2.3.0,<3.0.0)",
    "qdrant-client (>=1.14.2,<2.0.0)",
    "tree-sitter (>=0.24.0,<0.25.0)",
    "tree-sitter-python (>=0.23.6,<0.24.0)",
    "tree-sitter-java (>=0.23.5,<0.24.0)",
    "tree-sitter-cpp (>=0.23.4,<0.24.0)",
]

[tool.poetry]
packages = [{ include = "auto_fingerprint", from = "src" }]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
